Update docrep
xgcm/xgcm pull request #384
Opened 2021-12-01 21:30 UTC by TomNicholas

An attempt to fix #308.

This PR actually just completely removes the need for docrep at all - @jbusecke and I attempted to [update docrep](https://docrep.readthedocs.io/en/latest/#changed-in-0-3) to v0.3 but kept getting errors we didn't understand (in particular this one https://github.com/xgcm/xgcm/issues/210).

So we used the nuclear option to remove docrep by literally just copying and pasting the duplicated docstrings... :confused: 

That's annoying to have to do, but in fact we should probably wait until the [grid ufunc refactor](https://github.com/xgcm/xgcm/projects/10) is complete before trying to fix this situation/reinstate docrep, because that refactor will change how these docstrings all relate to one another anyway.

 - [x] Closes #308
 - [x] Passes `pre-commit run --all-files`

2021-12-01 21:53 UTC, jbusecke requested changes
Just minor stuff in addition to removing `vector_partner` from most of the docstrings. Otherwise I support this nuclear option for now.

2021-12-01 21:53 UTC, jbusecke commented on xgcm/grid.py
> +        vector_partner : dict, optional
I believe the 'vector_partner' input is only valid for the methods ending in `_vector`, and should be removed from all others.

2021-12-01 21:53 UTC, jbusecke commented on xgcm/grid.py
> +        vector_partner : dict, optional
remove (see comment below)

2021-12-01 21:53 UTC, jbusecke commented on xgcm/grid.py
> +            Optionally a dict with seperate values for each axis can be passed (see example)
The `(see example)` does not apply?

2021-12-01 22:02 UTC, jbusecke commented on xgcm/grid.py
> +        vector_partner : dict, optional
Sorry this is actually false. This only applies to certain methods, namely: `cumint` and `cumsum`.

2021-12-01 22:19 UTC, jbusecke commented
Could you rephrase

```
metric_weighted : str or tuple of str or dict, optional
            If an axis or list of axes is specified,
            the appropriate grid metrics will be used to determined the weight for interpolation.
            E.g. if passing `metric_weighted=['X', 'Y']`, values will be weighted by horizontal area.
            If `False` (default), the points will be weighted equally.
            Optionally a dict with seperate values for each axis can be passed (see example)
```

to 

```
metric_weighted : str or tuple of str or dict, optional
            Optionally use metrics to multiply/divide with appropriate metrics before/after the operation.
            E.g. if passing `metric_weighted=['X', 'Y']`, values will be weighted by horizontal area.
            If `False` (default), the points will be weighted equally.
            Optionally a dict with seperate values for each axis can be passed.
```

Otherwise this looks good to me. Thanks a lot @TomNicholas.

2021-12-01 22:19 UTC, jbusecke approved these changes

2021-12-01 22:52 UTC, merged

2021-12-02 03:18 UTC, rabernat commented
Thanks so much for taking care of this chore Tom! 👏

2021-12-02 20:17 UTC, nbren12 commented
Thanks! Doing God's work here!